//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace vbotserver.VBotService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="VBotServiceBinding", Namespace="urn:VBotService")]
    public partial class VBotService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback WhoAmIOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListForumsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListParentForumsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public VBotService() {
            this.Url = global::vbotserver.Properties.Settings.Default.vbotserver_VBotService_VBotService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event WhoAmICompletedEventHandler WhoAmICompleted;
        
        /// <remarks/>
        public event ListForumsCompletedEventHandler ListForumsCompleted;
        
        /// <remarks/>
        public event ListParentForumsCompletedEventHandler ListParentForumsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.anothermessageboard.com/vbulletinbot.php/WhoAmI", RequestNamespace="http://www.anothermessageboard.com", ResponseNamespace="http://www.anothermessageboard.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public RequestResult WhoAmI(UserCredentials UserCredentials) {
            object[] results = this.Invoke("WhoAmI", new object[] {
                        UserCredentials});
            return ((RequestResult)(results[0]));
        }
        
        /// <remarks/>
        public void WhoAmIAsync(UserCredentials UserCredentials) {
            this.WhoAmIAsync(UserCredentials, null);
        }
        
        /// <remarks/>
        public void WhoAmIAsync(UserCredentials UserCredentials, object userState) {
            if ((this.WhoAmIOperationCompleted == null)) {
                this.WhoAmIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWhoAmIOperationCompleted);
            }
            this.InvokeAsync("WhoAmI", new object[] {
                        UserCredentials}, this.WhoAmIOperationCompleted, userState);
        }
        
        private void OnWhoAmIOperationCompleted(object arg) {
            if ((this.WhoAmICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WhoAmICompleted(this, new WhoAmICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.anothermessageboard.com/vbulletinbot.php/ListForums", RequestNamespace="http://www.anothermessageboard.com", ResponseNamespace="http://www.anothermessageboard.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public ForumListResult ListForums(UserCredentials UserCredentials, int ForumID) {
            object[] results = this.Invoke("ListForums", new object[] {
                        UserCredentials,
                        ForumID});
            return ((ForumListResult)(results[0]));
        }
        
        /// <remarks/>
        public void ListForumsAsync(UserCredentials UserCredentials, int ForumID) {
            this.ListForumsAsync(UserCredentials, ForumID, null);
        }
        
        /// <remarks/>
        public void ListForumsAsync(UserCredentials UserCredentials, int ForumID, object userState) {
            if ((this.ListForumsOperationCompleted == null)) {
                this.ListForumsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListForumsOperationCompleted);
            }
            this.InvokeAsync("ListForums", new object[] {
                        UserCredentials,
                        ForumID}, this.ListForumsOperationCompleted, userState);
        }
        
        private void OnListForumsOperationCompleted(object arg) {
            if ((this.ListForumsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListForumsCompleted(this, new ListForumsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.anothermessageboard.com/vbulletinbot.php/ListParentForums", RequestNamespace="http://www.anothermessageboard.com", ResponseNamespace="http://www.anothermessageboard.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public ForumListResult ListParentForums(UserCredentials UserCredentials, int ForumID) {
            object[] results = this.Invoke("ListParentForums", new object[] {
                        UserCredentials,
                        ForumID});
            return ((ForumListResult)(results[0]));
        }
        
        /// <remarks/>
        public void ListParentForumsAsync(UserCredentials UserCredentials, int ForumID) {
            this.ListParentForumsAsync(UserCredentials, ForumID, null);
        }
        
        /// <remarks/>
        public void ListParentForumsAsync(UserCredentials UserCredentials, int ForumID, object userState) {
            if ((this.ListParentForumsOperationCompleted == null)) {
                this.ListParentForumsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListParentForumsOperationCompleted);
            }
            this.InvokeAsync("ListParentForums", new object[] {
                        UserCredentials,
                        ForumID}, this.ListParentForumsOperationCompleted, userState);
        }
        
        private void OnListParentForumsOperationCompleted(object arg) {
            if ((this.ListParentForumsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListParentForumsCompleted(this, new ListParentForumsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:VBotService")]
    public partial class UserCredentials {
        
        private string usernameField;
        
        private string serviceNameField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceName {
            get {
                return this.serviceNameField;
            }
            set {
                this.serviceNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:VBotService")]
    public partial class Forum {
        
        private int forumIDField;
        
        private string titleField;
        
        private bool isNewField;
        
        private bool isCurrentField;
        
        /// <remarks/>
        public int ForumID {
            get {
                return this.forumIDField;
            }
            set {
                this.forumIDField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public bool IsNew {
            get {
                return this.isNewField;
            }
            set {
                this.isNewField = value;
            }
        }
        
        /// <remarks/>
        public bool IsCurrent {
            get {
                return this.isCurrentField;
            }
            set {
                this.isCurrentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:VBotService")]
    public partial class ForumListResult {
        
        private RequestResult resultField;
        
        private Forum currentForumField;
        
        private Forum[] forumListField;
        
        /// <remarks/>
        public RequestResult Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public Forum CurrentForum {
            get {
                return this.currentForumField;
            }
            set {
                this.currentForumField = value;
            }
        }
        
        /// <remarks/>
        public Forum[] ForumList {
            get {
                return this.forumListField;
            }
            set {
                this.forumListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:VBotService")]
    public partial class RequestResult {
        
        private int codeField;
        
        private string textField;
        
        private RemoteUser remoteUserField;
        
        /// <remarks/>
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        public RemoteUser RemoteUser {
            get {
                return this.remoteUserField;
            }
            set {
                this.remoteUserField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:VBotService")]
    public partial class RemoteUser {
        
        private int userIDField;
        
        private string usernameField;
        
        /// <remarks/>
        public int UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void WhoAmICompletedEventHandler(object sender, WhoAmICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WhoAmICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WhoAmICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RequestResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RequestResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ListForumsCompletedEventHandler(object sender, ListForumsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListForumsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListForumsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ForumListResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ForumListResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ListParentForumsCompletedEventHandler(object sender, ListParentForumsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListParentForumsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListParentForumsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ForumListResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ForumListResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591