#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vbotserver
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="vbot")]
	public partial class VBotDB : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUserLastList(UserLastList instance);
    partial void UpdateUserLastList(UserLastList instance);
    partial void DeleteUserLastList(UserLastList instance);
    partial void InsertUserPostIndex(UserPostIndex instance);
    partial void UpdateUserPostIndex(UserPostIndex instance);
    partial void DeleteUserPostIndex(UserPostIndex instance);
    #endregion
		
		public VBotDB(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VBotDB(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VBotDB(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VBotDB(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<UserLastList> UserLastLists
		{
			get
			{
				return this.GetTable<UserLastList>();
			}
		}
		
		public System.Data.Linq.Table<UserPostIndex> UserPostIndexes
		{
			get
			{
				return this.GetTable<UserPostIndex>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class UserLastList : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserLastListID;
		
		private System.Nullable<int> _LocalUserID;
		
		private string _Name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserLastListIDChanging(int value);
    partial void OnUserLastListIDChanged();
    partial void OnLocalUserIDChanging(System.Nullable<int> value);
    partial void OnLocalUserIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public UserLastList()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserLastListID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UserLastListID
		{
			get
			{
				return this._UserLastListID;
			}
			set
			{
				if ((this._UserLastListID != value))
				{
					this.OnUserLastListIDChanging(value);
					this.SendPropertyChanging();
					this._UserLastListID = value;
					this.SendPropertyChanged("UserLastListID");
					this.OnUserLastListIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocalUserID", DbType="Int")]
		public System.Nullable<int> LocalUserID
		{
			get
			{
				return this._LocalUserID;
			}
			set
			{
				if ((this._LocalUserID != value))
				{
					this.OnLocalUserIDChanging(value);
					this.SendPropertyChanging();
					this._LocalUserID = value;
					this.SendPropertyChanged("LocalUserID");
					this.OnLocalUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class UserPostIndex : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserPostIndexID;
		
		private System.Nullable<int> _LocalUserID;
		
		private System.Nullable<int> _PostIndex;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserPostIndexIDChanging(int value);
    partial void OnUserPostIndexIDChanged();
    partial void OnLocalUserIDChanging(System.Nullable<int> value);
    partial void OnLocalUserIDChanged();
    partial void OnPostIndexChanging(System.Nullable<int> value);
    partial void OnPostIndexChanged();
    #endregion
		
		public UserPostIndex()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserPostIndexID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UserPostIndexID
		{
			get
			{
				return this._UserPostIndexID;
			}
			set
			{
				if ((this._UserPostIndexID != value))
				{
					this.OnUserPostIndexIDChanging(value);
					this.SendPropertyChanging();
					this._UserPostIndexID = value;
					this.SendPropertyChanged("UserPostIndexID");
					this.OnUserPostIndexIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocalUserID", DbType="Int")]
		public System.Nullable<int> LocalUserID
		{
			get
			{
				return this._LocalUserID;
			}
			set
			{
				if ((this._LocalUserID != value))
				{
					this.OnLocalUserIDChanging(value);
					this.SendPropertyChanging();
					this._LocalUserID = value;
					this.SendPropertyChanged("LocalUserID");
					this.OnLocalUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostIndex", DbType="Int")]
		public System.Nullable<int> PostIndex
		{
			get
			{
				return this._PostIndex;
			}
			set
			{
				if ((this._PostIndex != value))
				{
					this.OnPostIndexChanging(value);
					this.SendPropertyChanging();
					this._PostIndex = value;
					this.SendPropertyChanged("PostIndex");
					this.OnPostIndexChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
